#!/bin/bash -e

if [[ ! -f "$1" ]]; then
    echo "Usage: jobhours <Org-mode file containing CLOCK data>"
    exit 1
fi

if [[ ! -x "$(which jq)" ]]; then
    echo "Error: jobhours requires the 'jq' utility to be installed"
    exit 1
fi

if [[ ! -x "$(which org2tc)" ]]; then
    echo "Error: jobhours requires the 'org2tc' utility to be installed"
    exit 1
fi

function parseorg() {
    ORG_START=$(echo "$1" | cut -c-19)
    ORG_END=$(echo "$2" | cut -c-19)

    org2tc -s "$ORG_START" -e "$ORG_END" "$3"                   \
        | timelog-periods --begin "$1" --end "$2" --file -
}

periods=$(mktemp -t bae-periods.XXXXXXXX)
function finish {
  rm -f "$periods"
}
trap finish EXIT

bae-periods --there > "$periods"

START=$(jq -r .start "$periods")
FINISH=$(jq -r .finish "$periods")

process-hours --ideal "$periods" --real <(parseorg "$START" "$FINISH" "$1")
