name:       hours
version:    3.0.0
synopsis:   Tool to print out hours worked toward a goal
author:     John Wiegley
maintainer: johnw@newartisans.com
github:     jwiegley/hours
category:   System
license:    MIT

dependencies:
  - aeson                >= 1.2.3  && < 2.1
  - base                 >= 4      && < 5
  - bytestring           >= 0.10.8 && < 1.0
  - colour               >= 2.3.4  && < 3.0
  - mtl                  >= 2.2.1  && < 3.0
  - optparse-applicative >= 0.5.2  && < 1.0
  - text                 >= 1.2.2  && < 2.0
  - these                >= 0.7.4  && < 2
  - time                 >= 1.4    && < 2.0
  - time-recurrence      >= 0.9.1  && < 1.0

library:
  source-dirs: src
  exposed-modules:
    - Hours.Budget
    - Hours.Calc
    - Hours.Input
    - Hours.Time
    - Hours.Variant

executables:
  process-hours:
    main: Main.hs
    dependencies:
      - hours
      - diagrams
      - diagrams-cairo
      - diagrams-core
      - diagrams-lib

  work-periods:
    source-dirs: work
    main: Main.hs
    other-modules:
      - Work
    dependencies:
      - hours

  timelog-periods:
    source-dirs: timelog
    main: Main.hs
    other-modules:
      - Timelog
    dependencies:
      - hours
